name: scene_3d
description: 3D library for Dart.
version: 0.0.1
author: R.S. Schermer <roland0507@gmail.com>
homepage: https://github.com/RSSchermer/bagl.dart
documentation:
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  bagl:
    git: 'git://github.com/RSSchermer/bagl.dart.git'
  barback: '^0.15.2'
  code_transformers: '>=0.4.2 <1.0.0'
  inline_assets: '>=0.1.0 <0.2.0'
  glsl_include_transformer: '>=0.1.1 <0.2.0'
  path: '>=1.3.9 <1.4.0'
  source_span: '>=1.2.3 <2.0.0'
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^0.1.0'
transformers:
  - glsl_include_transformer
  - inline_assets
