name: scene_3d
description: 3D library for Dart.
version: 0.0.1
author: R.S. Schermer <roland0507@gmail.com>
homepage: https://github.com/RSSchermer/bagl.dart
documentation:
environment:
  sdk: '>=1.19.0 <2.0.0'
dependencies:
  bagl:
    git: 'git://github.com/RSSchermer/bagl.dart.git'
  inline_assets: '^0.1.0'
  glsl_include_transformer: '^0.1.3'
  observable: '^0.20.1'
  quiver: '^0.24.0'
dev_dependencies:
  test: '^0.12.17'
  browser: '^0.10.0'
  dart_to_js_script_rewriter: '^0.1.0'
transformers:
  - glsl_include_transformer
  - inline_assets
